### ISSUE TITLE
Hook up filter box

### ISSUE THREAD

**Issue by bowmanmc** [codefordayton/metroparks-tribute#17]
The filter box should filter results shown on the map as well as the results list

**Comment by jefferey** [comment]
I started on this a little. It now populates the Park and Type filter boxes with unique values from the data.

**Comment by jefferey** [comment]
Park and Type filters are now applied. Need more filter fields.

**Comment by jefferey** [comment]
Remove Search button.

**Comment by jefferey** [comment]
Done.
