### ISSUE TITLE
Figure out Tabletop.js (or other Google Spreadsheet -> JSON readers) for this project.

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/metroparks-tribute#3]

**Comment by dwcaraway** [comment]
[Google Spreadsheet](https://docs.google.com/spreadsheets/d/1rOgUf2f6PwxUKVUZ9RgmO6Ulhh5PquNuFvNROovvd1w/edit#gid=0)
[Tabletop Javascript Library](https://github.com/jsoma/tabletop)

Maybe add a script tag to CDN hosted library

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/tabletop.js/1.4.3/tabletop.min.js"></script>
```
